from typing import Protocol

from app.core.models import Metadata, SceneQueries, Script, Topic


class LLMProvider(Protocol):
    async def generate_topic(self, recent: list[str]) -> Topic: ...
    async def generate_script(self, topic: Topic) -> Script: ...
    async def generate_metadata(self, script: Script) -> Metadata: ...
    async def generate_scene_queries(self, script: Script) -> SceneQueries: ...
